### PR TITLE
1.10

### PR DESCRIPTION
**Pull request by DoughnutDev**

### CODE REVIEW

**Comment by Dream-Master** [comment]
Hope this works not checked it.

**Comment by Dream-Master** [comment]
@DoughnutDev Thanks.

**Comment by DoughnutDev** [comment]
@Dream-Master Not sure if it worked or not

**Comment by Dream-Master** [comment]
Why you not commit it to the 1.10 branch.

**Comment by Techlone** [comment]
@Dream-Master you should revert this PR and @DoughnutDev should make a new PR in the 1.10 branch not the master

**Comment by Dream-Master** [comment]
@Techlone Sorry screwed up need help.

**Comment by DoughnutDev** [comment]
Something is still messed up I am working on it now.

**Comment by Dream-Master** [comment]
ok thanks

**Pull request merged**
