### PR TITLE
1.10

### PR DESCRIPTION
**Pull request by DoughnutDev**

### CODE REVIEW

**Comment by DoughnutDev** [comment]
@Dream-Master @Techlone You should take a look at this. I was missing some classes, but something I noticed is that in the machine classes it is removing big portions of code when I setup the mod with the new CraftTweaker (MineTweaker) version.

**Comment by Dream-Master** [comment]
@DoughnutDev @Techlone 
I add you to the team so you can change code not need to make pull requests.

**Comment by Dream-Master** [comment]
@DoughnutDev I add you as a contributor so you can merge it by yourself. @Techlone i add you also.
Help me fix this mess would be nice. Thanks.

**Comment by Techlone** [comment]
@DoughnutDev why did you make PRs into the master branch? Master it's 1.7.10 version not 1.10.

**Comment by Techlone** [comment]
I close the PR because you missed a branch again

**Pull request closed without merging**
